languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 2

title = "Congo"
copyright = "&copy; 2023 Congo contributors"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

[params.author]
  name = "Kevin Fu"
  image = "img/author.jpg"
  headline = "Not your ordinary theme!"
  bio = "Sofware developer/Investor/Dreamer"
  links = [
    { youtube = "https://www.youtube.com/channel/UCBogzranpJg2nn42gUFFeIg" },
  ]