languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 2

title = "Maplefubaba"
copyright = "&copy; 2024 Kevin Fu"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "Blog"

[params.author]
  name = "Kevin Fu"
  image = "img/author.jpg"
  headline = "Welcome to my blog!"
  bio = "Sofware developer/Engineer/Investor/Dreamer"
  links = [
    { youtube = "https://www.youtube.com/channel/UCBogzranpJg2nn42gUFFeIg" },
  ]